FROM arm32v7/gcc

RUN apt-get update && \
    apt-get install -y \
        make \
        git \
        wget \
        libssl-dev \
        zlib1g-dev \
        bzip2 \
        && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ADD . /app

ENV DROPBEAR_VERSION=2024.86

RUN ./configure --enable-static
RUN make -j8 PROGRAMS="dropbear dbclient dropbearkey dropbearconvert scp" MULTI=1
