CFLAGS = /I../src/headers/ /I./ /Ox /DWIN32 /W3 /Fo$@

OBJECTS=base64_test.obj cipher_hash_test.obj der_tests.obj dh_tests.obj \
dsa_test.obj ecc_test.obj mac_test.obj modes_test.obj pkcs_1_test.obj \
rsa_test.obj store_test.obj test.obj x86_prof.obj

tomcrypt_prof.lib: $(OBJECTS)
	lib /out:tomcrypt_prof.lib $(OBJECTS)


