#MSVC Makefile
#
#Tom St Denis

CFLAGS = /I../ /Ogityb2 /Gs /DWIN32 /W3

pprime: pprime.obj
	cl pprime.obj ../tommath.lib 

mersenne: mersenne.obj
	cl mersenne.obj ../tommath.lib
	
tune: tune.obj
	cl tune.obj ../tommath.lib
	
drprime: drprime.obj
	cl drprime.obj ../tommath.lib